### ISSUE TITLE
LUKS drive

### ISSUE THREAD

**Issue by krillin666** [PabloLec/RecoverPy#110]
Hey,

Great tool! Is it possible to use on a LUKS encrypted drive? When I try I get an error.

**Comment by PabloLec** [comment]
Hi, no there is no way to read an encrypted file or partition. Well, you can read it but its content is going to be encrypted.

What kind of error do you read by the way? I'm curious to know. Maybe Linux doesn't even let you have read access?

**Comment by panporter** [comment]
Your code should already work on decrypted and mounted LUKS-devices.

But here's the problem:

https://github.com/PabloLec/RecoverPy/blob/e71528f38cf7afc6c6bc46a88c36102bae3e110f/recoverpy/models/partition.py#L6C1-L13C35

`get_full_name()` of class Partition returns `"/dev/{self.name}"`. This works for partitions like sda1 and the like and returns `"/dev/sda1"`.

But decrypted LUKS-partitions reside in /dev/**mapper**/luks-[some_unique_id], but 
`get_full_name()` returns `"/dev/luks-[some_unique_id]"` which leads to nowhere.

So you have to keep track in your Partition class whether the partition is a LUKS partition and add /mapper/ to the path in `get_full_name()`.

How to find out?
`lsblk -r -n -o "NAME,TYPE,FSTYPE,MOUNTPOINT"` returns 
`luks-[some_unique_id] crypt ext4 /mountpoint`

so a TYPE == "crypt" is a LUKS-partition.

Better yet:

If you use `lsblk -r -n -o "NAME,TYPE,FSTYPE,MOUNTPOINT,PATH"` then PATH is your correct answer for `get_full_name()`.

e.g.
/dev/**mapper**/[name] for LUKS (or LVM)
/dev/sdX otherwise.


HTH.
