### ISSUE TITLE
Recover from mounted file

### ISSUE THREAD

**Issue by coz-eduardo-hernandez** [PabloLec/RecoverPy#454]
Hello,

in https://github.com/PabloLec/RecoverPy/issues/275 the requester wanted to look through an unmounted IMG file. He was suggested to mount it and try to look through it. However the file does not appear in RecoverPy, even though it is in lsblk, which I suspect that is because it gets filtered out because the lsblk entry classifies it as 'loop':

`loop28         7:28   0 189.5G  1 loop /mnt/windows`

Could the filtering be made optional?

**Comment by PabloLec** [comment]
Hello @coz-eduardo-hernandez, and thank you for highlighting this issue.

Indeed, I just tested creating an IMG file and mounting it, and it shows up as loop in lsblk.
Originally, RecoverPy filters out loop mount points because, in my experience, snap daemon multiplies the loop mount points, which is a disaster. I hadn't realized that this type of mount (IMG and similar) was identified as loop.

I'll try to work on this issue soon, ideally this weekend.
I think a good solution would be to dynamically enable/disable filtering on the TUI, on the partitions screen, keeping the filtering enabled by default.

Anyway, I'll keep you updated on the development. In my view, #275 didn't bring up this issue, but with your context, I can see the connection. Nevertheless, it definitely is an issue that needs addressing.

**Comment by coz-eduardo-hernandez** [comment]
Indeed there are many loop mount points of no interest. You can see on the previous post that the loop is 'loop28', so there are 27 loop entries before that one of no interest to me

The problem to solve in #275 was different, and going through the img file directly would be nice to have, specially if the block is too corrupted to be mounted, but it sounds like it's not a trivial addition

I did go through the source, and I didn't actually commit the changes I ended up making. I removed the loop filtering on my public commit, but it doesn't work (I think it's because the code loops over the tuple later, but I didn't confirm it), so I ended replacing the 'loop' string with 'dummy' and that did work. I didn't actually add a toggle because I didn't want to learn how to use the UI library used in RecoverPy

I did manage to recover quite a few files I couldn't recover otherwise since text files have no header, and many other tools rely on detecting headers to do file carving, so you have my thanks for this tool

**Comment by PabloLec** [comment]
Hi @coz-eduardo-hernandez, I just added that checkbox. It's located at the bottom right of the screen with the list of partitions. 
I just released version 2.1.8 with this feature. The release might take some time to propagate on PyPI though. Let me know if you encounter any issues.
