### ISSUE TITLE
Finding not all partitions in my system

### ISSUE THREAD

**Issue by lylklb** [PabloLec/recoverpy#5]
My system has the following two partition, but the recoverpy only finds the partition vda2 for root system....
Notes: the other partition vdb for vghana must be umounted due to some special causes(e.g. security or damaged)
 
```
# pvs
  PV         VG     Fmt  Attr PSize   PFree
  /dev/vda2  system lvm2 a--   82.00g 20.00g
  /dev/vdb   vghana lvm2 a--  800.00g  5.00g
```

**Comment by PabloLec** [comment]
Recoverpy uses this command under the hood:

```
lsblk -rno NAME,TYPE,FSTYPE,MOUNTPOINT
```

If `lsblk` does not list your partition, then here is your problem.
Here, I see that you're working with a Red Hat VM and only have logical volumes.

If your partition is not displayed by `lsblk` when unmounted, then that's probably that your system does not have access to it at all and it won't be compatible with `grep` even if you try manually.

How these LVM are mounted? 
You don't have access to any physical volume in your environment?
To avoid all the hassle maybe you should find where are your physical volumes that hold these LVMs and use these physical vols rather than logical ones. But maybe you can't do it in your current system.

That is not related to recoverpy but to your environment. I can try to help a bit, even though I'm not an expert in this field. I'm having an eye on unix stack exchange right now.
Anyhow, you should investigate why your logical volume is not listed in `lsblk`, how to make it visible in it and know if this is possible at all.

**Comment by lylklb** [comment]
As you can see,  it does have the other partition vdb for vghana in the following lsblk output ....

```
# lsblk -rno NAME,TYPE,FSTYPE,MOUNTPOINT
loop0 loop iso9660 /mnt/cdrom
loop1 loop btrfs 
loop2 loop  
loop3 loop  
loop4 loop  
vda disk  
vda1 part  
vda2 part LVM2_member 
vdb disk LVM2_member 
system-root lvm btrfs /
system-swap lvm swap [SWAP]
vghana-lvhana lvm btrfs 
# 
```

**Comment by PabloLec** [comment]
My bad I thought `lsblk` wasn't listing all of your partitions. I'll check tomorrow why your unmounted LVM does not appear and release a fix if possible.

**Comment by PabloLec** [comment]
Can you confirm how many lines do appear in recoverpy and which ones ?

**Comment by lylklb** [comment]
Yes,   just only one line！

```
── Select a partition to search:
   Name: vda2  -  Type: LVM2_member      
```

**Comment by PabloLec** [comment]
I uploaded a quick fix that should do the trick. 
So it was ignoring your loopback lines, which is normal, also ignoring lines where no filesystem is detected, again on purpose.
But lines like `system-root lvm btrfs /` where ignored because its type is `lvm` and not `part`. I didn't expected that indeed.

So, now it's fixed, all the relevant lines should be displayed. I hope `lvm` parts are compatible with grep.
I tested with your `lsblk` output but feel free to tell me if it's working in you environment.

**Comment by lylklb** [comment]
Now it should be all right with the DISK PARTITIONs,  except for the LVM entry.

```
# cat  recoverpy-2021-05-20-124528.log
Starting 'ParametersMenu' CUI window
User is root
Partition list generated using 'lsblk'
5 partitions found
Partition added to list: vda2
Partition added to list: vdb
Partition added to list: system-root
Partition added to list: system-swap
Partition added to list: vghana-lvhana
#

```
So if you select some LVM entry,  the recoverpy would exit with the following errors: 

```
File "/usr/lib/python3.6/site-packages/recoverpy/parameters_menu.py", line 178, in select_partition
    selected_partition = re.findall(r"Name\:\ ([A-Za-z0-9]+)\ ", self.partition_list_cell.get())[0]
IndexError: list index out of range
```

**Comment by PabloLec** [comment]
I see, I opened Issue #7.
